### ISSUE TITLE
Does not work with QWERTZ layout

### ISSUE THREAD

**Issue by idleberg** [MauriceZ/AppendSemiColon#1]
Unfortunately, this package does not work with the German keyboard layout (QWERTZ) and possibly other non-QWERTY layouts. The semicolon requires to hold the shift key (<kbd>Shift</kbd>+<kbd>,</kbd>), so that's probably the reason.

I have tried changing the user keybindings, but this had no effect. My guess is, that you have to add support to custom keybindings, so that your package shows up in _Preferences > Package Settings_.

**Comment by MauriceZ** [comment]
Thanks for reporting the issue, I'll add custom keybindings ASAP

**Comment by MauriceZ** [comment]
You can now add custom keybindings in 1.1.0
