### ISSUE TITLE
Unusable on spanish Keybard

### ISSUE THREAD

**Issue by eduardoarandah** [MauriceZ/AppendSemiColon#4]
Spanish keyboard needs to use shift to create a semicolon, 
so I need to press ctrl+shift+ (the key that has semicolon)

Would be great being able to customize hotkey

https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/spanish_notebook.png

**Comment by MauriceZ** [comment]
It should already be possible to customize the hotkeys. Go in Preferences > Package Settings > AppendSemiColon

**Comment by eduardoarandah** [comment]
thanks!
didn't know that option existed
