### ISSUE TITLE
Please change the default shortcut

### ISSUE THREAD

**Issue by ptsl** [MauriceZ/AppendSemiColon#5]
Thank you for creating AppendSemiColon!

The default shortcut for AppendSemiColon is "ctrl+;". This shadows ST3's own "ctrl+;" shortcut, which pops up the "Goto Term" dialog. Though this is easily configurable, I think that you should not override ST's default shortcuts. And Goto Term is quite an important dialog.

AppendComma uses "ctrl+alt+," and "ctrl+alt+shift+," respectively. Maybe you should use the Alt key in your shortcuts as well.

**Comment by MauriceZ** [comment]
Sorry, that would be a breaking change and the shortcut can easily be changed. If more requests for this come up, I'll consider changing the default shortcut. Thanks for the feedback though!
